services:
  kpi-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kpi-streamlit
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
      TZ: "America/Bogota"
      FRESHDESK_DOMAIN: ${FRESHDESK_DOMAIN:-}
      FRESHDESK_API_KEY: ${FRESHDESK_API_KEY:-}
    volumes:
      - ./datasources:/app/datasources
    restart: unless-stopped
